apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.wrongWayDriver.name }}
data:
  appsettings.Production.json: |
    {
      "Kafka": {
          "bootstrap": {
              "servers": "{{ .Values.kafka.server }}"
          },
          "sasl": {
              "mechanism": "{{.Values.kafka.security.mechanism}}",
              "username": "{{ .Values.kafka.userName }}"
          },
          "security": {
               "protocol": "{{.Values.kafka.security.protocol}}"
          },
          "GroupId": "{{ .Values.wrongWayDriver.kafka.groupId }}"
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.wrongWayDriver.name }}
  labels:
    app: {{ .Values.wrongWayDriver.name }}
    chart: {{ .Values.wrongWayDriver.name }}
    release: {{ .Release.Name }}
  annotations:
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.wrongWayDriver.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.wrongWayDriver.name }}
        release: {{ .Release.Name }}
      annotations:
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              release: {{ .Release.Name }}
      imagePullSecrets:
        - name: {{ .Values.secrets.imagePullSecret }}
      volumes:
        - name: config
          configMap:
            name: {{ .Values.wrongWayDriver.name }}
        - name: data
          emptyDir:
            sizeLimit: 100Mi
      containers:
        - name: {{ .Values.wrongWayDriver.name }}
          image: "{{ .Values.wrongWayDriver.imageRepository }}:{{ .Values.wrongWayDriver.imageTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: Kafka__sasl__password
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.kafka.userName }}
                  key: password
          volumeMounts:
            - name: config
              mountPath: /app/appsettings.Production.json
              subPath: appsettings.Production.json
              readOnly: true
            - name: data
              mountPath: /app/data
              readOnly: false
          resources:
{{ toYaml .Values.wrongWayDriver.resources | indent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.wrongWayDriver.name }}
  labels:
    app: {{ .Values.wrongWayDriver.name }}
    chart: {{ .Values.wrongWayDriver.name }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.wrongWayDriver.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.wrongWayDriver.name }}
    release: {{ .Release.Name }}